
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Thu Apr 30 12:29:30 CEST 2020
//----------------------------------------------------

package syntactical;

/**
 * CUP generated class containing symbol constants.
 */
public class ClassConstants {
    /* terminals */
    public static final int MULT = 28;
    public static final int CHAR = 52;
    public static final int CONST = 9;
    public static final int ASSIGNMENT = 40;
    public static final int GE = 35;
    public static final int EQUALS = 38;
    public static final int PLUS_ASSIGN = 23;
    public static final int INT = 50;
    public static final int FOR = 5;
    public static final int MINUS = 26;
    public static final int AND = 42;
    public static final int NOT = 41;
    public static final int LT = 34;
    public static final int TYPE = 48;
    public static final int OR = 43;
    public static final int IN = 7;
    public static final int ELLIPSIS = 20;
    public static final int COMMA = 22;
    public static final int CLASS = 10;
    public static final int DIV = 30;
    public static final int PLUS = 24;
    public static final int IF = 2;
    public static final int THIS = 47;
    public static final int LE = 33;
    public static final int EOF = 0;
    public static final int RETURN = 8;
    public static final int TRUE = 54;
    public static final int error = 1;
    public static final int SQUARE_R = 16;
    public static final int NULL = 57;
    public static final int MOD = 32;
    public static final int GLOBAL = 46;
    public static final int NEQ = 39;
    public static final int CURLY_R = 18;
    public static final int SQUARE_L = 15;
    public static final int DIV_ASSIGN = 29;
    public static final int SWITCH = 4;
    public static final int MOD_ASSIGN = 31;
    public static final int REAL = 51;
    public static final int IMPORT = 49;
    public static final int CURLY_L = 17;
    public static final int ARROW = 19;
    public static final int ELSE = 3;
    public static final int POINT = 21;
    public static final int WHILE = 6;
    public static final int CONSTRUCTOR = 11;
    public static final int IDENTITY = 37;
    public static final int END = 44;
    public static final int UNDERSCORE = 12;
    public static final int STRING = 53;
    public static final int NOTHING = 56;
    public static final int FALSE = 55;
    public static final int PARENTH_R = 14;
    public static final int MULT_ASSIGN = 27;
    public static final int GT = 36;
    public static final int MINUS_ASSIGN = 25;
    public static final int PARENTH_L = 13;
    public static final int IDENTIFIER = 45;
}

