
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 28 20:12:19 CEST 2020
//----------------------------------------------------

package syntactical;

/** CUP generated class containing symbol constants. */
public class ClassConstants {
  /* terminals */
  public static final int MULT = 29;
  public static final int CHAR = 52;
  public static final int CONST = 9;
  public static final int ASSIGNMENT = 41;
  public static final int GE = 36;
  public static final int EQUALS = 39;
  public static final int PLUS_ASSIGN = 24;
  public static final int INT = 50;
  public static final int FOR = 5;
  public static final int MINUS = 27;
  public static final int AND = 43;
  public static final int NOT = 42;
  public static final int LT = 35;
  public static final int TYPE = 48;
  public static final int OR = 44;
  public static final int IN = 7;
  public static final int ELLIPSIS = 21;
  public static final int COMMA = 23;
  public static final int CLASS = 10;
  public static final int DIV = 31;
  public static final int PLUS = 25;
  public static final int IF = 2;
  public static final int THIS = 12;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 8;
  public static final int TRUE = 54;
  public static final int error = 1;
  public static final int SQUARE_R = 17;
  public static final int NULL = 57;
  public static final int MOD = 33;
  public static final int GLOBAL = 47;
  public static final int NEQ = 40;
  public static final int CURLY_R = 19;
  public static final int SQUARE_L = 16;
  public static final int DIV_ASSIGN = 30;
  public static final int SWITCH = 4;
  public static final int MOD_ASSIGN = 32;
  public static final int REAL = 51;
  public static final int IMPORT = 49;
  public static final int CURLY_L = 18;
  public static final int ARROW = 20;
  public static final int ELSE = 3;
  public static final int POINT = 22;
  public static final int WHILE = 6;
  public static final int CONSTRUCTOR = 11;
  public static final int IDENTITY = 38;
  public static final int END = 45;
  public static final int UNDERSCORE = 13;
  public static final int STRING = 53;
  public static final int NOTHING = 56;
  public static final int FALSE = 55;
  public static final int PARENTH_R = 15;
  public static final int MULT_ASSIGN = 28;
  public static final int GT = 37;
  public static final int MINUS_ASSIGN = 26;
  public static final int PARENTH_L = 14;
  public static final int IDENTIFIER = 46;
}

