
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 14 17:56:47 CEST 2020
//----------------------------------------------------

package syntactical;

/**
 * CUP generated class containing symbol constants.
 */
public class ClassConstants {
    /* terminals */
    public static final int MULT = 37;
    public static final int CONST = 17;
    public static final int CHAR = 4;
    public static final int ASSIGNMENT = 49;
    public static final int GE = 44;
    public static final int EQUALS = 47;
    public static final int PLUS_ASSIGN = 32;
    public static final int INT = 2;
    public static final int MINUS = 35;
    public static final int FOR = 9;
    public static final int AND = 51;
    public static final int NOT = 50;
    public static final int LT = 43;
    public static final int OR = 52;
    public static final int IN = 11;
    public static final int ELLIPSIS = 29;
    public static final int COMMA = 31;
    public static final int CLASS = 18;
    public static final int DIV = 39;
    public static final int PLUS = 33;
    public static final int IF = 6;
    public static final int THIS = 20;
    public static final int LE = 42;
    public static final int EOF = 0;
    public static final int RETURN = 12;
    public static final int TRUE = 13;
    public static final int error = 1;
    public static final int SQUARE_R = 25;
    public static final int NULL = 16;
    public static final int MOD = 41;
    public static final int NEQ = 48;
    public static final int CURLY_R = 27;
    public static final int SQUARE_L = 24;
    public static final int MOD_ASSIGN = 40;
    public static final int DIV_ASSIGN = 38;
    public static final int SWITCH = 8;
    public static final int IMPORT = 55;
    public static final int REAL = 3;
    public static final int CURLY_L = 26;
    public static final int ARROW = 28;
    public static final int ELSE = 7;
    public static final int POINT = 30;
    public static final int WHILE = 10;
    public static final int CONSTRUCTOR = 19;
    public static final int IDENTITY = 46;
    public static final int END = 53;
    public static final int UNDERSCORE = 21;
    public static final int STRING = 5;
    public static final int NOTHING = 15;
    public static final int FALSE = 14;
    public static final int PARENTH_R = 23;
    public static final int MULT_ASSIGN = 36;
    public static final int GT = 45;
    public static final int MINUS_ASSIGN = 34;
    public static final int PARENTH_L = 22;
    public static final int IDENTIFIER = 54;
}

